// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	TWITCH_USER_ID: string;
	TWITCH_CLIENT_ID: string;
	TWITCH_APP_ACCESS_TOKEN: string;
}
